/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Args
 */
export interface Args {
}
/**
 * 
 * @export
 * @interface AudioUrl
 */
export interface AudioUrl {
    /**
     * 
     * @type {string}
     * @memberof AudioUrl
     */
    'url': string;
    /**
     * 
     * @type {boolean}
     * @memberof AudioUrl
     */
    'force_download'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AudioUrl
     */
    'vendor_metadata'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof AudioUrl
     */
    'media_type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AudioUrl
     */
    'identifier'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AudioUrl
     */
    'kind'?: AudioUrlKindEnum;
}

export const AudioUrlKindEnum = {
    AudioUrl: 'audio-url'
} as const;

export type AudioUrlKindEnum = typeof AudioUrlKindEnum[keyof typeof AudioUrlKindEnum];

/**
 * 
 * @export
 * @interface BinaryContent
 */
export interface BinaryContent {
    /**
     * 
     * @type {File}
     * @memberof BinaryContent
     */
    'data': File;
    /**
     * 
     * @type {MediaType}
     * @memberof BinaryContent
     */
    'media_type': MediaType;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof BinaryContent
     */
    'vendor_metadata'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof BinaryContent
     */
    'identifier'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BinaryContent
     */
    'kind'?: BinaryContentKindEnum;
}

export const BinaryContentKindEnum = {
    Binary: 'binary'
} as const;

export type BinaryContentKindEnum = typeof BinaryContentKindEnum[keyof typeof BinaryContentKindEnum];

/**
 * 
 * @export
 * @interface BuiltinToolCallPart
 */
export interface BuiltinToolCallPart {
    /**
     * 
     * @type {string}
     * @memberof BuiltinToolCallPart
     */
    'tool_name': string;
    /**
     * 
     * @type {Args}
     * @memberof BuiltinToolCallPart
     */
    'args'?: Args | null;
    /**
     * 
     * @type {string}
     * @memberof BuiltinToolCallPart
     */
    'tool_call_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof BuiltinToolCallPart
     */
    'provider_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BuiltinToolCallPart
     */
    'part_kind'?: BuiltinToolCallPartPartKindEnum;
}

export const BuiltinToolCallPartPartKindEnum = {
    BuiltinToolCall: 'builtin-tool-call'
} as const;

export type BuiltinToolCallPartPartKindEnum = typeof BuiltinToolCallPartPartKindEnum[keyof typeof BuiltinToolCallPartPartKindEnum];

/**
 * 
 * @export
 * @interface BuiltinToolReturnPart
 */
export interface BuiltinToolReturnPart {
    /**
     * 
     * @type {string}
     * @memberof BuiltinToolReturnPart
     */
    'tool_name': string;
    /**
     * 
     * @type {any}
     * @memberof BuiltinToolReturnPart
     */
    'content': any;
    /**
     * 
     * @type {string}
     * @memberof BuiltinToolReturnPart
     */
    'tool_call_id'?: string;
    /**
     * 
     * @type {any}
     * @memberof BuiltinToolReturnPart
     */
    'metadata'?: any;
    /**
     * 
     * @type {string}
     * @memberof BuiltinToolReturnPart
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof BuiltinToolReturnPart
     */
    'provider_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BuiltinToolReturnPart
     */
    'part_kind'?: BuiltinToolReturnPartPartKindEnum;
}

export const BuiltinToolReturnPartPartKindEnum = {
    BuiltinToolReturn: 'builtin-tool-return'
} as const;

export type BuiltinToolReturnPartPartKindEnum = typeof BuiltinToolReturnPartPartKindEnum[keyof typeof BuiltinToolReturnPartPartKindEnum];

/**
 * 
 * @export
 * @interface ChatRequest
 */
export interface ChatRequest {
    /**
     * 
     * @type {Array<ChatRequestMessagesInner>}
     * @memberof ChatRequest
     */
    'messages': Array<ChatRequestMessagesInner>;
}
/**
 * @type ChatRequestMessagesInner
 * @export
 */
export type ChatRequestMessagesInner = { kind: 'request' } & ModelRequest | { kind: 'response' } & ModelResponse;

/**
 * 
 * @export
 * @interface Content
 */
export interface Content {
}
/**
 * 
 * @export
 * @interface Content1
 */
export interface Content1 {
}
/**
 * 
 * @export
 * @interface Content1AnyOfInner
 */
export interface Content1AnyOfInner {
    /**
     * 
     * @type {string}
     * @memberof Content1AnyOfInner
     */
    'url': string;
    /**
     * 
     * @type {boolean}
     * @memberof Content1AnyOfInner
     */
    'force_download'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof Content1AnyOfInner
     */
    'vendor_metadata'?: { [key: string]: any; };
    /**
     * 
     * @type {MediaType}
     * @memberof Content1AnyOfInner
     */
    'media_type': MediaType;
    /**
     * 
     * @type {string}
     * @memberof Content1AnyOfInner
     */
    'identifier'?: string;
    /**
     * 
     * @type {string}
     * @memberof Content1AnyOfInner
     */
    'kind'?: Content1AnyOfInnerKindEnum;
    /**
     * 
     * @type {File}
     * @memberof Content1AnyOfInner
     */
    'data': File;
}

export const Content1AnyOfInnerKindEnum = {
    Binary: 'binary'
} as const;

export type Content1AnyOfInnerKindEnum = typeof Content1AnyOfInnerKindEnum[keyof typeof Content1AnyOfInnerKindEnum];

/**
 * 
 * @export
 * @interface DocumentUrl
 */
export interface DocumentUrl {
    /**
     * 
     * @type {string}
     * @memberof DocumentUrl
     */
    'url': string;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentUrl
     */
    'force_download'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof DocumentUrl
     */
    'vendor_metadata'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentUrl
     */
    'media_type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentUrl
     */
    'identifier'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentUrl
     */
    'kind'?: DocumentUrlKindEnum;
}

export const DocumentUrlKindEnum = {
    DocumentUrl: 'document-url'
} as const;

export type DocumentUrlKindEnum = typeof DocumentUrlKindEnum[keyof typeof DocumentUrlKindEnum];

/**
 * 
 * @export
 * @interface ErrorDetails
 */
export interface ErrorDetails {
    /**
     * 
     * @type {string}
     * @memberof ErrorDetails
     */
    'type': string;
    /**
     * 
     * @type {Array<ErrorDetailsLocInner>}
     * @memberof ErrorDetails
     */
    'loc': Array<ErrorDetailsLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ErrorDetails
     */
    'msg': string;
    /**
     * 
     * @type {any}
     * @memberof ErrorDetails
     */
    'input': any;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ErrorDetails
     */
    'ctx'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof ErrorDetails
     */
    'url'?: string;
}
/**
 * 
 * @export
 * @interface ErrorDetailsLocInner
 */
export interface ErrorDetailsLocInner {
}
/**
 * 
 * @export
 * @interface FilePart
 */
export interface FilePart {
    /**
     * 
     * @type {BinaryContent}
     * @memberof FilePart
     */
    'content': BinaryContent;
    /**
     * 
     * @type {string}
     * @memberof FilePart
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FilePart
     */
    'provider_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FilePart
     */
    'part_kind'?: FilePartPartKindEnum;
}

export const FilePartPartKindEnum = {
    File: 'file'
} as const;

export type FilePartPartKindEnum = typeof FilePartPartKindEnum[keyof typeof FilePartPartKindEnum];

/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface ImageUrl
 */
export interface ImageUrl {
    /**
     * 
     * @type {string}
     * @memberof ImageUrl
     */
    'url': string;
    /**
     * 
     * @type {boolean}
     * @memberof ImageUrl
     */
    'force_download'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ImageUrl
     */
    'vendor_metadata'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof ImageUrl
     */
    'media_type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageUrl
     */
    'identifier'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageUrl
     */
    'kind'?: ImageUrlKindEnum;
}

export const ImageUrlKindEnum = {
    ImageUrl: 'image-url'
} as const;

export type ImageUrlKindEnum = typeof ImageUrlKindEnum[keyof typeof ImageUrlKindEnum];

/**
 * 
 * @export
 * @interface MediaType
 */
export interface MediaType {
}
/**
 * 
 * @export
 * @interface ModelRequest
 */
export interface ModelRequest {
    /**
     * 
     * @type {Array<ModelRequestPartsInner>}
     * @memberof ModelRequest
     */
    'parts': Array<ModelRequestPartsInner>;
    /**
     * 
     * @type {string}
     * @memberof ModelRequest
     */
    'instructions'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModelRequest
     */
    'kind'?: ModelRequestKindEnum;
}

export const ModelRequestKindEnum = {
    Request: 'request'
} as const;

export type ModelRequestKindEnum = typeof ModelRequestKindEnum[keyof typeof ModelRequestKindEnum];

/**
 * @type ModelRequestPartsInner
 * @export
 */
export type ModelRequestPartsInner = { part_kind: 'retry-prompt' } & RetryPromptPart | { part_kind: 'system-prompt' } & SystemPromptPart | { part_kind: 'tool-return' } & ToolReturnPart | { part_kind: 'user-prompt' } & UserPromptPart;

/**
 * 
 * @export
 * @interface ModelResponse
 */
export interface ModelResponse {
    /**
     * 
     * @type {Array<ModelResponsePartsInner>}
     * @memberof ModelResponse
     */
    'parts': Array<ModelResponsePartsInner>;
    /**
     * 
     * @type {RequestUsage}
     * @memberof ModelResponse
     */
    'usage'?: RequestUsage;
    /**
     * 
     * @type {string}
     * @memberof ModelResponse
     */
    'model_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModelResponse
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelResponse
     */
    'kind'?: ModelResponseKindEnum;
    /**
     * 
     * @type {string}
     * @memberof ModelResponse
     */
    'provider_name'?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ModelResponse
     */
    'provider_details'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof ModelResponse
     */
    'provider_response_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ModelResponse
     */
    'finish_reason'?: ModelResponseFinishReasonEnum | null;
}

export const ModelResponseKindEnum = {
    Response: 'response'
} as const;

export type ModelResponseKindEnum = typeof ModelResponseKindEnum[keyof typeof ModelResponseKindEnum];
export const ModelResponseFinishReasonEnum = {
    Stop: 'stop',
    Length: 'length',
    ContentFilter: 'content_filter',
    ToolCall: 'tool_call',
    Error: 'error'
} as const;

export type ModelResponseFinishReasonEnum = typeof ModelResponseFinishReasonEnum[keyof typeof ModelResponseFinishReasonEnum];

/**
 * @type ModelResponsePartsInner
 * @export
 */
export type ModelResponsePartsInner = { part_kind: 'builtin-tool-call' } & BuiltinToolCallPart | { part_kind: 'builtin-tool-return' } & BuiltinToolReturnPart | { part_kind: 'file' } & FilePart | { part_kind: 'text' } & TextPart | { part_kind: 'thinking' } & ThinkingPart | { part_kind: 'tool-call' } & ToolCallPart;

/**
 * 
 * @export
 * @interface RequestUsage
 */
export interface RequestUsage {
    /**
     * 
     * @type {number}
     * @memberof RequestUsage
     */
    'input_tokens'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUsage
     */
    'cache_write_tokens'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUsage
     */
    'cache_read_tokens'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUsage
     */
    'output_tokens'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUsage
     */
    'input_audio_tokens'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUsage
     */
    'cache_audio_read_tokens'?: number;
    /**
     * 
     * @type {number}
     * @memberof RequestUsage
     */
    'output_audio_tokens'?: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof RequestUsage
     */
    'details'?: { [key: string]: number; };
}
/**
 * 
 * @export
 * @interface RetryPromptPart
 */
export interface RetryPromptPart {
    /**
     * 
     * @type {Content}
     * @memberof RetryPromptPart
     */
    'content': Content;
    /**
     * 
     * @type {string}
     * @memberof RetryPromptPart
     */
    'tool_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RetryPromptPart
     */
    'tool_call_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof RetryPromptPart
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof RetryPromptPart
     */
    'part_kind'?: RetryPromptPartPartKindEnum;
}

export const RetryPromptPartPartKindEnum = {
    RetryPrompt: 'retry-prompt'
} as const;

export type RetryPromptPartPartKindEnum = typeof RetryPromptPartPartKindEnum[keyof typeof RetryPromptPartPartKindEnum];

/**
 * 
 * @export
 * @interface SystemPromptPart
 */
export interface SystemPromptPart {
    /**
     * 
     * @type {string}
     * @memberof SystemPromptPart
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof SystemPromptPart
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof SystemPromptPart
     */
    'dynamic_ref'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SystemPromptPart
     */
    'part_kind'?: SystemPromptPartPartKindEnum;
}

export const SystemPromptPartPartKindEnum = {
    SystemPrompt: 'system-prompt'
} as const;

export type SystemPromptPartPartKindEnum = typeof SystemPromptPartPartKindEnum[keyof typeof SystemPromptPartPartKindEnum];

/**
 * 
 * @export
 * @interface TextPart
 */
export interface TextPart {
    /**
     * 
     * @type {string}
     * @memberof TextPart
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof TextPart
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TextPart
     */
    'part_kind'?: TextPartPartKindEnum;
}

export const TextPartPartKindEnum = {
    Text: 'text'
} as const;

export type TextPartPartKindEnum = typeof TextPartPartKindEnum[keyof typeof TextPartPartKindEnum];

/**
 * 
 * @export
 * @interface ThinkingPart
 */
export interface ThinkingPart {
    /**
     * 
     * @type {string}
     * @memberof ThinkingPart
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof ThinkingPart
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ThinkingPart
     */
    'signature'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ThinkingPart
     */
    'provider_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ThinkingPart
     */
    'part_kind'?: ThinkingPartPartKindEnum;
}

export const ThinkingPartPartKindEnum = {
    Thinking: 'thinking'
} as const;

export type ThinkingPartPartKindEnum = typeof ThinkingPartPartKindEnum[keyof typeof ThinkingPartPartKindEnum];

/**
 * 
 * @export
 * @interface ToolCallPart
 */
export interface ToolCallPart {
    /**
     * 
     * @type {string}
     * @memberof ToolCallPart
     */
    'tool_name': string;
    /**
     * 
     * @type {Args}
     * @memberof ToolCallPart
     */
    'args'?: Args | null;
    /**
     * 
     * @type {string}
     * @memberof ToolCallPart
     */
    'tool_call_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ToolCallPart
     */
    'part_kind'?: ToolCallPartPartKindEnum;
}

export const ToolCallPartPartKindEnum = {
    ToolCall: 'tool-call'
} as const;

export type ToolCallPartPartKindEnum = typeof ToolCallPartPartKindEnum[keyof typeof ToolCallPartPartKindEnum];

/**
 * 
 * @export
 * @interface ToolReturnPart
 */
export interface ToolReturnPart {
    /**
     * 
     * @type {string}
     * @memberof ToolReturnPart
     */
    'tool_name': string;
    /**
     * 
     * @type {any}
     * @memberof ToolReturnPart
     */
    'content': any;
    /**
     * 
     * @type {string}
     * @memberof ToolReturnPart
     */
    'tool_call_id'?: string;
    /**
     * 
     * @type {any}
     * @memberof ToolReturnPart
     */
    'metadata'?: any;
    /**
     * 
     * @type {string}
     * @memberof ToolReturnPart
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof ToolReturnPart
     */
    'part_kind'?: ToolReturnPartPartKindEnum;
}

export const ToolReturnPartPartKindEnum = {
    ToolReturn: 'tool-return'
} as const;

export type ToolReturnPartPartKindEnum = typeof ToolReturnPartPartKindEnum[keyof typeof ToolReturnPartPartKindEnum];

/**
 * 
 * @export
 * @interface UserPromptPart
 */
export interface UserPromptPart {
    /**
     * 
     * @type {Content1}
     * @memberof UserPromptPart
     */
    'content': Content1;
    /**
     * 
     * @type {string}
     * @memberof UserPromptPart
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPromptPart
     */
    'part_kind'?: UserPromptPartPartKindEnum;
}

export const UserPromptPartPartKindEnum = {
    UserPrompt: 'user-prompt'
} as const;

export type UserPromptPartPartKindEnum = typeof UserPromptPartPartKindEnum[keyof typeof UserPromptPartPartKindEnum];

/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}
/**
 * 
 * @export
 * @interface VideoUrl
 */
export interface VideoUrl {
    /**
     * 
     * @type {string}
     * @memberof VideoUrl
     */
    'url': string;
    /**
     * 
     * @type {boolean}
     * @memberof VideoUrl
     */
    'force_download'?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof VideoUrl
     */
    'vendor_metadata'?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof VideoUrl
     */
    'media_type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoUrl
     */
    'identifier'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VideoUrl
     */
    'kind'?: VideoUrlKindEnum;
}

export const VideoUrlKindEnum = {
    VideoUrl: 'video-url'
} as const;

export type VideoUrlKindEnum = typeof VideoUrlKindEnum[keyof typeof VideoUrlKindEnum];


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Simple streaming chat endpoint.
         * @summary Chat
         * @param {ChatRequest} chatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatChatPost: async (chatRequest: ChatRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatRequest' is not null or undefined
            assertParamExists('chatChatPost', 'chatRequest', chatRequest)
            const localVarPath = `/chat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(chatRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Simple streaming chat endpoint.
         * @summary Chat
         * @param {ChatRequest} chatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatChatPost(chatRequest: ChatRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatChatPost(chatRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.chatChatPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Simple streaming chat endpoint.
         * @summary Chat
         * @param {DefaultApiChatChatPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatChatPost(requestParameters: DefaultApiChatChatPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.chatChatPost(requestParameters.chatRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - interface
 * @export
 * @interface DefaultApi
 */
export interface DefaultApiInterface {
    /**
     * Simple streaming chat endpoint.
     * @summary Chat
     * @param {DefaultApiChatChatPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    chatChatPost(requestParameters: DefaultApiChatChatPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<any>;

}

/**
 * Request parameters for chatChatPost operation in DefaultApi.
 * @export
 * @interface DefaultApiChatChatPostRequest
 */
export interface DefaultApiChatChatPostRequest {
    /**
     * 
     * @type {ChatRequest}
     * @memberof DefaultApiChatChatPost
     */
    readonly chatRequest: ChatRequest
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     * Simple streaming chat endpoint.
     * @summary Chat
     * @param {DefaultApiChatChatPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public chatChatPost(requestParameters: DefaultApiChatChatPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).chatChatPost(requestParameters.chatRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



